services:
  web:
    container_name: DRE
    image: rpcw2024tp/webapp
    ports:
      - "5000:5000"
    depends_on:
      - gdb
    links:
      - gdb
  gdb:
    container_name: graphdb_RPCWTP
    image: khaller/graphdb-free
    ports:
      - "7200:7200"